### ISSUE TITLE
1.2.5 crashes meteor 1.11 build

### ISSUE THREAD

**Issue by dearlordylord** [mhagmajer/server-router#11]
`meteor --version` => `Meteor 1.11`

An example project created with `meteor create --minimal`: https://github.com/Firfi/meteor-server-router-example

Crash message:

```
W20200831-15:17:02.731(7)? (STDERR) /Users/firfi/work/clients/darren/router-test/.meteor/local/build/programs/server/packages/mhagmajer_server-router.js:138
W20200831-15:17:02.794(7)? (STDERR) type Path = {|
node_modules/
W20200831-15:17:02.795(7)? (STDERR)      ^^^^
W20200831-15:17:02.795(7)? (STDERR)
W20200831-15:17:02.796(7)? (STDERR) SyntaxError: Unexpected identifier
node_modules/
W20200831-15:17:02.797(7)? (STDERR)     at new Script (vm.js:88:7)
W20200831-15:17:02.797(7)? (STDERR)     at createScript (vm.js:261:10)
W20200831-15:17:02.797(7)? (STDERR)     at Object.runInThisContext (vm.js:309:10)
W20200831-15:17:02.798(7)? (STDERR)     at /Users/firfi/work/clients/darren/router-test/.meteor/local/build/programs/server/boot.js:384:32
W20200831-15:17:02.798(7)? (STDERR)     at Array.forEach (<anonymous>)
W20200831-15:17:02.798(7)? (STDERR)     at /Users/firfi/work/clients/darren/router-test/.meteor/local/build/programs/server/boot.js:226:21
W20200831-15:17:02.799(7)? (STDERR)     at /Users/firfi/work/clients/darren/router-test/.meteor/local/build/programs/server/boot.js:464:7
W20200831-15:17:02.799(7)? (STDERR)     at Function.run (/Users/firfi/work/clients/darren/router-test/.meteor/local/build/programs/server/profile.js:280:14)
W20200831-15:17:02.799(7)? (STDERR)     at /Users/firfi/work/clients/darren/router-test/.meteor/local/build/programs/server/boot.js:463:13
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

**Comment by dearlordylord** [comment]
I believe it's related to https://github.com/mhagmajer/server-router/issues/9

1.2.5 introduces the proposed solution https://github.com/meteor/meteor/blob/devel/History.md#v1102-2020-04-21 indeed but it doesn't work for some reason.
